[package]
name = "rust-validation-serde-valid"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_valid = "0.19"
serde_json = "1.0"
actix-web = "4"
