[package]
name = "rust-validation-validator"
version = "0.1.0"
edition = "2024"

[dependencies]
validator = { version = "0.19", features = ["derive"] }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }